from dataclasses import dataclass

@dataclass
class PlcConfig:
    host: str = "127.0.0.1"
    port: int = 502
    unit_id: int = 1
    heartbeat_register: int = 0
    marker_register: int = 10

    # NOWE:
    safe_write_register: int = 2   # np. %MW2 – setpoint
    safe_write_min: int = 0        # minimalna „bezpieczna” wartość
    safe_write_max: int = 1000     # maksymalna „bezpieczna” wartość

def get_plc_config() -> PlcConfig:
    return PlcConfig()
